import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Roboto, Inter } from "next/font/google";
import "./globals.css";

const geistPopins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400"],
});

const geistPopinsMedium = Poppins({
  variable: "--font-poppins-medium",
  subsets: ["latin"],
  weight: ["500"],
});

const geistInter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["500"],
});
const geistRoboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${geistPopins.variable} ${geistInter.variable} ${geistRoboto.variable} ${geistPopinsMedium.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
